version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: nottify_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nottify-network

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - nottify-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/nottify_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

networks:
  nottify-network:

volumes:
  postgres_data:
